ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS accent_color VARCHAR(20) DEFAULT '#2644ec';
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS accent_bg VARCHAR(40) DEFAULT 'rgba(59, 85, 255, 0.1)';
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS accent_border VARCHAR(40) DEFAULT 'rgba(59, 85, 255, 0.5)';
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS text_color VARCHAR(20) DEFAULT '#6b6375';
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS text_heading_color VARCHAR(20) DEFAULT '#08060d';
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS bg_color VARCHAR(20) DEFAULT '#ffffff';
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS border_color VARCHAR(20) DEFAULT '#e5e4e7';
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS code_bg_color VARCHAR(20) DEFAULT '#f4f3ec';

-- Dark mode overrides
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS dark_accent_color VARCHAR(20) DEFAULT '#c084fc';
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS dark_accent_bg VARCHAR(40) DEFAULT 'rgba(192, 132, 252, 0.15)';
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS dark_accent_border VARCHAR(40) DEFAULT 'rgba(192, 132, 252, 0.5)';
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS dark_text_color VARCHAR(20) DEFAULT '#9ca3af';
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS dark_text_heading_color VARCHAR(20) DEFAULT '#f3f4f6';
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS dark_bg_color VARCHAR(20) DEFAULT '#16171d';
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS dark_border_color VARCHAR(20) DEFAULT '#2e303a';
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS dark_code_bg_color VARCHAR(20) DEFAULT '#1f2028';

-- Font settings
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS heading_font VARCHAR(255);
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS mono_font VARCHAR(255);
ALTER TABLE brand_kit ADD COLUMN IF NOT EXISTS base_font_size VARCHAR(10) DEFAULT '18px';
