// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blog_posts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBlogPosts = `-- name: CountBlogPosts :one
SELECT COUNT(*) FROM blog_posts WHERE ($1::text = '' OR status = $1::text)
`

func (q *Queries) CountBlogPosts(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countBlogPosts, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlogPost = `-- name: CreateBlogPost :one
INSERT INTO blog_posts (title, slug, content, excerpt, cover_image, status, author_id, published_at, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at
`

type CreateBlogPostParams struct {
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Content     pgtype.Text      `json:"content"`
	Excerpt     pgtype.Text      `json:"excerpt"`
	CoverImage  pgtype.Text      `json:"cover_image"`
	Status      pgtype.Text      `json:"status"`
	AuthorID    pgtype.UUID      `json:"author_id"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	Metadata    []byte           `json:"metadata"`
}

type CreateBlogPostRow struct {
	ID        pgtype.UUID      `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateBlogPost(ctx context.Context, arg CreateBlogPostParams) (CreateBlogPostRow, error) {
	row := q.db.QueryRow(ctx, createBlogPost,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Excerpt,
		arg.CoverImage,
		arg.Status,
		arg.AuthorID,
		arg.PublishedAt,
		arg.Metadata,
	)
	var i CreateBlogPostRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteBlogPost = `-- name: DeleteBlogPost :exec
DELETE FROM blog_posts WHERE id = $1
`

func (q *Queries) DeleteBlogPost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlogPost, id)
	return err
}

const getBlogPostByID = `-- name: GetBlogPostByID :one
SELECT id, title, slug, content, excerpt, cover_image, status, author_id, created_at, published_at, metadata
FROM blog_posts WHERE id = $1
`

func (q *Queries) GetBlogPostByID(ctx context.Context, id pgtype.UUID) (BlogPost, error) {
	row := q.db.QueryRow(ctx, getBlogPostByID, id)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.CoverImage,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Metadata,
	)
	return i, err
}

const getBlogPostBySlug = `-- name: GetBlogPostBySlug :one
SELECT id, title, slug, content, excerpt, cover_image, status, author_id, created_at, published_at, metadata
FROM blog_posts WHERE slug = $1
`

func (q *Queries) GetBlogPostBySlug(ctx context.Context, slug string) (BlogPost, error) {
	row := q.db.QueryRow(ctx, getBlogPostBySlug, slug)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.CoverImage,
		&i.Status,
		&i.AuthorID,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.Metadata,
	)
	return i, err
}

const listBlogPosts = `-- name: ListBlogPosts :many
SELECT id, title, slug, content, excerpt, cover_image, status, author_id, created_at, published_at, metadata
FROM blog_posts
WHERE ($1::text = '' OR status = $1::text)
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListBlogPostsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListBlogPosts(ctx context.Context, arg ListBlogPostsParams) ([]BlogPost, error) {
	rows, err := q.db.Query(ctx, listBlogPosts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlogPost{}
	for rows.Next() {
		var i BlogPost
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Content,
			&i.Excerpt,
			&i.CoverImage,
			&i.Status,
			&i.AuthorID,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlogPost = `-- name: UpdateBlogPost :exec
UPDATE blog_posts
SET title = $1, slug = $2, content = $3, excerpt = $4, cover_image = $5,
    status = $6, author_id = $7, published_at = $8, metadata = $9
WHERE id = $10
`

type UpdateBlogPostParams struct {
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Content     pgtype.Text      `json:"content"`
	Excerpt     pgtype.Text      `json:"excerpt"`
	CoverImage  pgtype.Text      `json:"cover_image"`
	Status      pgtype.Text      `json:"status"`
	AuthorID    pgtype.UUID      `json:"author_id"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	Metadata    []byte           `json:"metadata"`
	ID          pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateBlogPost(ctx context.Context, arg UpdateBlogPostParams) error {
	_, err := q.db.Exec(ctx, updateBlogPost,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Excerpt,
		arg.CoverImage,
		arg.Status,
		arg.AuthorID,
		arg.PublishedAt,
		arg.Metadata,
		arg.ID,
	)
	return err
}
