// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminTool struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Url         string      `json:"url"`
	Icon        pgtype.Text `json:"icon"`
	Category    pgtype.Text `json:"category"`
	IsActive    pgtype.Bool `json:"is_active"`
	MinRole     pgtype.Text `json:"min_role"`
	OrderIndex  pgtype.Int4 `json:"order_index"`
}

type AppLog struct {
	ID        int64            `json:"id"`
	Level     string           `json:"level"`
	Message   string           `json:"message"`
	Source    pgtype.Text      `json:"source"`
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type AuditLog struct {
	ID         pgtype.UUID      `json:"id"`
	UserID     pgtype.UUID      `json:"user_id"`
	Action     string           `json:"action"`
	Resource   pgtype.Text      `json:"resource"`
	ResourceID pgtype.Text      `json:"resource_id"`
	Details    []byte           `json:"details"`
	IpAddress  pgtype.Text      `json:"ip_address"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Banner struct {
	ID              pgtype.UUID      `json:"id"`
	Title           pgtype.Text      `json:"title"`
	ImageUrl        string           `json:"image_url"`
	LinkUrl         pgtype.Text      `json:"link_url"`
	TargetProfile   pgtype.Text      `json:"target_profile"`
	IsActive        pgtype.Bool      `json:"is_active"`
	StartDate       pgtype.Timestamp `json:"start_date"`
	EndDate         pgtype.Timestamp `json:"end_date"`
	DisplayDuration pgtype.Int4      `json:"display_duration"`
	CacheKey        pgtype.Text      `json:"cache_key"`
	OrderIndex      pgtype.Int4      `json:"order_index"`
}

type BlogPost struct {
	ID          pgtype.UUID      `json:"id"`
	Title       string           `json:"title"`
	Slug        string           `json:"slug"`
	Content     pgtype.Text      `json:"content"`
	Excerpt     pgtype.Text      `json:"excerpt"`
	CoverImage  pgtype.Text      `json:"cover_image"`
	Status      pgtype.Text      `json:"status"`
	AuthorID    pgtype.UUID      `json:"author_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	Metadata    []byte           `json:"metadata"`
}

type BrandKit struct {
	ID                   pgtype.UUID      `json:"id"`
	PrimaryColor         pgtype.Text      `json:"primary_color"`
	SecondaryColor       pgtype.Text      `json:"secondary_color"`
	LogoUrl              pgtype.Text      `json:"logo_url"`
	FaviconUrl           pgtype.Text      `json:"favicon_url"`
	FontFamily           pgtype.Text      `json:"font_family"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	AccentColor          pgtype.Text      `json:"accent_color"`
	AccentBg             pgtype.Text      `json:"accent_bg"`
	AccentBorder         pgtype.Text      `json:"accent_border"`
	TextColor            pgtype.Text      `json:"text_color"`
	TextHeadingColor     pgtype.Text      `json:"text_heading_color"`
	BgColor              pgtype.Text      `json:"bg_color"`
	BorderColor          pgtype.Text      `json:"border_color"`
	CodeBgColor          pgtype.Text      `json:"code_bg_color"`
	DarkAccentColor      pgtype.Text      `json:"dark_accent_color"`
	DarkAccentBg         pgtype.Text      `json:"dark_accent_bg"`
	DarkAccentBorder     pgtype.Text      `json:"dark_accent_border"`
	DarkTextColor        pgtype.Text      `json:"dark_text_color"`
	DarkTextHeadingColor pgtype.Text      `json:"dark_text_heading_color"`
	DarkBgColor          pgtype.Text      `json:"dark_bg_color"`
	DarkBorderColor      pgtype.Text      `json:"dark_border_color"`
	DarkCodeBgColor      pgtype.Text      `json:"dark_code_bg_color"`
	HeadingFont          pgtype.Text      `json:"heading_font"`
	MonoFont             pgtype.Text      `json:"mono_font"`
	BaseFontSize         pgtype.Text      `json:"base_font_size"`
}

type Category struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Slug     pgtype.Text `json:"slug"`
	ParentID pgtype.UUID `json:"parent_id"`
}

type Coupon struct {
	ID            pgtype.UUID      `json:"id"`
	Code          string           `json:"code"`
	DiscountType  pgtype.Text      `json:"discount_type"`
	DiscountValue pgtype.Numeric   `json:"discount_value"`
	MinPurchase   pgtype.Numeric   `json:"min_purchase"`
	ValidFrom     pgtype.Timestamp `json:"valid_from"`
	ValidUntil    pgtype.Timestamp `json:"valid_until"`
	MaxUses       pgtype.Int4      `json:"max_uses"`
	UsedCount     pgtype.Int4      `json:"used_count"`
	IsActive      pgtype.Bool      `json:"is_active"`
}

type CronJob struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Schedule  string           `json:"schedule"`
	Handler   string           `json:"handler"`
	IsActive  pgtype.Bool      `json:"is_active"`
	LastRunAt pgtype.Timestamp `json:"last_run_at"`
	NextRunAt pgtype.Timestamp `json:"next_run_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type EmailGroup struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type EmailSubscription struct {
	ID           pgtype.UUID      `json:"id"`
	Email        string           `json:"email"`
	GroupID      pgtype.UUID      `json:"group_id"`
	IsActive     pgtype.Bool      `json:"is_active"`
	SubscribedAt pgtype.Timestamp `json:"subscribed_at"`
}

type FeatureFlag struct {
	ID        int32            `json:"id"`
	Key       string           `json:"key"`
	Enabled   pgtype.Bool      `json:"enabled"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type HealthCheck struct {
	ID          pgtype.UUID      `json:"id"`
	ServiceName string           `json:"service_name"`
	Status      string           `json:"status"`
	LatencyMs   pgtype.Int4      `json:"latency_ms"`
	Details     []byte           `json:"details"`
	CheckedAt   pgtype.Timestamp `json:"checked_at"`
}

type JobExecution struct {
	ID         pgtype.UUID      `json:"id"`
	JobID      pgtype.UUID      `json:"job_id"`
	Status     string           `json:"status"`
	StartedAt  pgtype.Timestamp `json:"started_at"`
	FinishedAt pgtype.Timestamp `json:"finished_at"`
	DurationMs pgtype.Int4      `json:"duration_ms"`
	Error      pgtype.Text      `json:"error"`
	Output     []byte           `json:"output"`
}

type LegalPage struct {
	ID        pgtype.UUID      `json:"id"`
	Slug      string           `json:"slug"`
	Title     string           `json:"title"`
	Content   string           `json:"content"`
	IsActive  pgtype.Bool      `json:"is_active"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type LinktreeItem struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	Url        string      `json:"url"`
	Icon       pgtype.Text `json:"icon"`
	OrderIndex pgtype.Int4 `json:"order_index"`
	IsActive   pgtype.Bool `json:"is_active"`
}

type LogConfig struct {
	ID            int32            `json:"id"`
	RetentionDays pgtype.Int4      `json:"retention_days"`
	MinLevel      pgtype.Text      `json:"min_level"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Order struct {
	ID              pgtype.UUID      `json:"id"`
	UserID          pgtype.UUID      `json:"user_id"`
	Status          pgtype.Text      `json:"status"`
	Total           pgtype.Numeric   `json:"total"`
	PaymentMethod   pgtype.Text      `json:"payment_method"`
	PaymentID       pgtype.Text      `json:"payment_id"`
	ShippingAddress []byte           `json:"shipping_address"`
	TrackingCode    pgtype.Text      `json:"tracking_code"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	ReceiptUrl      pgtype.Text      `json:"receipt_url"`
}

type OrderItem struct {
	ID        pgtype.UUID    `json:"id"`
	OrderID   pgtype.UUID    `json:"order_id"`
	ProductID pgtype.UUID    `json:"product_id"`
	Quantity  int32          `json:"quantity"`
	UnitPrice pgtype.Numeric `json:"unit_price"`
}

type PixConfig struct {
	ID          int32            `json:"id"`
	PixKey      string           `json:"pix_key"`
	KeyType     string           `json:"key_type"`
	Beneficiary string           `json:"beneficiary"`
	City        string           `json:"city"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Product struct {
	ID                 pgtype.UUID      `json:"id"`
	Name               string           `json:"name"`
	Description        pgtype.Text      `json:"description"`
	Price              pgtype.Numeric   `json:"price"`
	Stock              pgtype.Int4      `json:"stock"`
	IsPreSale          pgtype.Bool      `json:"is_pre_sale"`
	PreSaleAvailableAt pgtype.Timestamp `json:"pre_sale_available_at"`
	Images             []byte           `json:"images"`
	CategoryID         pgtype.UUID      `json:"category_id"`
	IsActive           pgtype.Bool      `json:"is_active"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

type SecuritySetting struct {
	ID          int32            `json:"id"`
	Key         string           `json:"key"`
	Value       string           `json:"value"`
	Description pgtype.Text      `json:"description"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID               pgtype.UUID      `json:"id"`
	Email            string           `json:"email"`
	PasswordHash     string           `json:"password_hash"`
	Name             pgtype.Text      `json:"name"`
	Role             pgtype.Text      `json:"role"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	EmailVerified    pgtype.Bool      `json:"email_verified"`
	EmailVerifiedAt  pgtype.Timestamp `json:"email_verified_at"`
	StripeCustomerID pgtype.Text      `json:"stripe_customer_id"`
}

type UserGroup struct {
	ID                 pgtype.UUID    `json:"id"`
	Name               string         `json:"name"`
	DiscountPercentage pgtype.Numeric `json:"discount_percentage"`
}

type UserProfile struct {
	ID        pgtype.UUID `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	Phone     pgtype.Text `json:"phone"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Address   []byte      `json:"address"`
	Metadata  []byte      `json:"metadata"`
}

type Waitlist struct {
	ID        pgtype.UUID      `json:"id"`
	Email     string           `json:"email"`
	Name      pgtype.Text      `json:"name"`
	Source    pgtype.Text      `json:"source"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
