// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products
WHERE ($1::uuid IS NULL OR category_id = $1)
  AND ($2::boolean = false OR is_active = true)
`

type CountProductsParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	ActiveOnly bool        `json:"active_only"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.CategoryID, arg.ActiveOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, description, price, stock, is_pre_sale, pre_sale_available_at, images, category_id, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at, updated_at
`

type CreateProductParams struct {
	Name               string           `json:"name"`
	Description        pgtype.Text      `json:"description"`
	Price              pgtype.Numeric   `json:"price"`
	Stock              pgtype.Int4      `json:"stock"`
	IsPreSale          pgtype.Bool      `json:"is_pre_sale"`
	PreSaleAvailableAt pgtype.Timestamp `json:"pre_sale_available_at"`
	Images             []byte           `json:"images"`
	CategoryID         pgtype.UUID      `json:"category_id"`
	IsActive           pgtype.Bool      `json:"is_active"`
}

type CreateProductRow struct {
	ID        pgtype.UUID      `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.IsPreSale,
		arg.PreSaleAvailableAt,
		arg.Images,
		arg.CategoryID,
		arg.IsActive,
	)
	var i CreateProductRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price, stock, is_pre_sale, pre_sale_available_at, images, category_id, is_active, created_at, updated_at
FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.IsPreSale,
		&i.PreSaleAvailableAt,
		&i.Images,
		&i.CategoryID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, price, stock, is_pre_sale, pre_sale_available_at, images, category_id, is_active, created_at, updated_at
FROM products
WHERE ($1::uuid IS NULL OR category_id = $1)
  AND ($2::boolean = false OR is_active = true)
ORDER BY created_at DESC LIMIT $4 OFFSET $3
`

type ListProductsParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	ActiveOnly bool        `json:"active_only"`
	RowOffset  int32       `json:"row_offset"`
	RowLimit   int32       `json:"row_limit"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.CategoryID,
		arg.ActiveOnly,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.IsPreSale,
			&i.PreSaleAvailableAt,
			&i.Images,
			&i.CategoryID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET name = $1, description = $2, price = $3, stock = $4, is_pre_sale = $5,
    pre_sale_available_at = $6, images = $7, category_id = $8, is_active = $9
WHERE id = $10
`

type UpdateProductParams struct {
	Name               string           `json:"name"`
	Description        pgtype.Text      `json:"description"`
	Price              pgtype.Numeric   `json:"price"`
	Stock              pgtype.Int4      `json:"stock"`
	IsPreSale          pgtype.Bool      `json:"is_pre_sale"`
	PreSaleAvailableAt pgtype.Timestamp `json:"pre_sale_available_at"`
	Images             []byte           `json:"images"`
	CategoryID         pgtype.UUID      `json:"category_id"`
	IsActive           pgtype.Bool      `json:"is_active"`
	ID                 pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.IsPreSale,
		arg.PreSaleAvailableAt,
		arg.Images,
		arg.CategoryID,
		arg.IsActive,
		arg.ID,
	)
	return err
}
