// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountBlogPosts(ctx context.Context, statusFilter string) (int64, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateBlogPost(ctx context.Context, arg CreateBlogPostParams) (CreateBlogPostRow, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (pgtype.UUID, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteBlogPost(ctx context.Context, id pgtype.UUID) error
	DeleteCategory(ctx context.Context, id pgtype.UUID) error
	DeleteProduct(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetBlogPostByID(ctx context.Context, id pgtype.UUID) (BlogPost, error)
	GetBlogPostBySlug(ctx context.Context, slug string) (BlogPost, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	ListBlogPosts(ctx context.Context, arg ListBlogPostsParams) ([]BlogPost, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	UpdateBlogPost(ctx context.Context, arg UpdateBlogPostParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateStripeCustomerID(ctx context.Context, arg UpdateStripeCustomerIDParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	VerifyEmail(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
