// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email_verified, email_verified_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         pgtype.Text `json:"name"`
	Role         pgtype.Text `json:"role"`
}

type CreateUserRow struct {
	ID              pgtype.UUID      `json:"id"`
	EmailVerified   pgtype.Bool      `json:"email_verified"`
	EmailVerifiedAt pgtype.Timestamp `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, role, email_verified, email_verified_at, stripe_customer_id, created_at, updated_at
FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID               pgtype.UUID      `json:"id"`
	Email            string           `json:"email"`
	PasswordHash     string           `json:"password_hash"`
	Name             pgtype.Text      `json:"name"`
	Role             pgtype.Text      `json:"role"`
	EmailVerified    pgtype.Bool      `json:"email_verified"`
	EmailVerifiedAt  pgtype.Timestamp `json:"email_verified_at"`
	StripeCustomerID pgtype.Text      `json:"stripe_customer_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, role, email_verified, email_verified_at, stripe_customer_id, created_at, updated_at
FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID               pgtype.UUID      `json:"id"`
	Email            string           `json:"email"`
	PasswordHash     string           `json:"password_hash"`
	Name             pgtype.Text      `json:"name"`
	Role             pgtype.Text      `json:"role"`
	EmailVerified    pgtype.Bool      `json:"email_verified"`
	EmailVerifiedAt  pgtype.Timestamp `json:"email_verified_at"`
	StripeCustomerID pgtype.Text      `json:"stripe_customer_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, name, role, email_verified, email_verified_at, stripe_customer_id, created_at, updated_at
FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID               pgtype.UUID      `json:"id"`
	Email            string           `json:"email"`
	PasswordHash     string           `json:"password_hash"`
	Name             pgtype.Text      `json:"name"`
	Role             pgtype.Text      `json:"role"`
	EmailVerified    pgtype.Bool      `json:"email_verified"`
	EmailVerifiedAt  pgtype.Timestamp `json:"email_verified_at"`
	StripeCustomerID pgtype.Text      `json:"stripe_customer_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Role,
			&i.EmailVerified,
			&i.EmailVerifiedAt,
			&i.StripeCustomerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStripeCustomerID = `-- name: UpdateStripeCustomerID :exec
UPDATE users SET stripe_customer_id = $1, updated_at = NOW() WHERE id = $2
`

type UpdateStripeCustomerIDParams struct {
	StripeCustomerID pgtype.Text `json:"stripe_customer_id"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateStripeCustomerID(ctx context.Context, arg UpdateStripeCustomerIDParams) error {
	_, err := q.db.Exec(ctx, updateStripeCustomerID, arg.StripeCustomerID, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET email = $1, password_hash = $2, name = $3, role = $4, updated_at = NOW()
WHERE id = $5
`

type UpdateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Name         pgtype.Text `json:"name"`
	Role         pgtype.Text `json:"role"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.ID,
	)
	return err
}

const verifyEmail = `-- name: VerifyEmail :exec
UPDATE users SET email_verified = true, email_verified_at = NOW() WHERE id = $1
`

func (q *Queries) VerifyEmail(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyEmail, id)
	return err
}
