#!/usr/bin/env bash
set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC}   $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# --- Guards ---

if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root."
    exit 1
fi

if [[ $# -lt 1 ]]; then
    error "Usage: $0 <domain>"
    echo "  Example: $0 example.com"
    exit 1
fi

DOMAIN="$1"
NGINX_CONF="/etc/nginx/sites-available/blueprint"
NGINX_ENABLED="/etc/nginx/sites-enabled/blueprint"

info "Configuring Nginx for domain: ${DOMAIN}"

# --- Nginx config ---

info "Writing ${NGINX_CONF} ..."

cat > "${NGINX_CONF}" <<NGINXEOF
# Blueprint Nginx Config
# Generated by setup-nginx.sh

# Rate limiting
limit_req_zone \$binary_remote_addr zone=api:10m rate=30r/s;
limit_req_zone \$binary_remote_addr zone=auth:10m rate=5r/s;

server {
    listen 80;
    server_name ${DOMAIN};
    return 301 https://\$server_name\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    # SSL (Certbot will fill these)
    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_stapling on;
    ssl_stapling_verify on;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    # Brotli compression
    brotli on;
    brotli_comp_level 6;
    brotli_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

    # Gzip fallback
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript image/svg+xml;

    # Frontend static files
    root /opt/blueprint/frontend;
    index index.html;

    # Static assets — long cache
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|webp|avif)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files \$uri =404;
    }

    # Service worker — no cache
    location = /sw.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        try_files \$uri =404;
    }

    # API proxy
    location /api/ {
        limit_req zone=api burst=20 nodelay;
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 120s;
    }

    # Auth endpoints — stricter rate limit
    location /api/v1/auth/ {
        limit_req zone=auth burst=5 nodelay;
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # SSE streaming (logs)
    location /api/v1/admin/logs/stream {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 86400s;
    }

    # Health check endpoint
    location /healthz {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
    }

    # Static uploads
    location /static/ {
        alias /opt/blueprint/uploads/;
        expires 30d;
        add_header Cache-Control "public";
    }

    # Health monitor dashboard (proxy to :8081)
    location /health {
        proxy_pass http://127.0.0.1:8081;
        proxy_http_version 1.1;
    }

    # pgweb (admin only — restrict by IP or basic auth in production)
    location /pgweb/ {
        proxy_pass http://127.0.0.1:8082/;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
    }

    # Grafana
    location /grafana/ {
        proxy_pass http://127.0.0.1:3000/;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
    }

    # SPA fallback — must be last
    location / {
        try_files \$uri \$uri/ /index.html;
    }
}
NGINXEOF

success "Wrote ${NGINX_CONF}"

# --- Enable site ---

info "Enabling site ..."
ln -sf "${NGINX_CONF}" "${NGINX_ENABLED}"
success "Symlinked to ${NGINX_ENABLED}"

# --- Remove default site if present ---

if [[ -f /etc/nginx/sites-enabled/default ]]; then
    rm -f /etc/nginx/sites-enabled/default
    success "Removed default site"
fi

# --- Test config ---

info "Testing Nginx configuration ..."
if nginx -t 2>&1; then
    success "Nginx configuration is valid"
else
    error "Nginx configuration test failed. Review ${NGINX_CONF} before reloading."
    exit 1
fi

# --- Certbot ---

echo ""
read -rp "$(echo -e "${YELLOW}Run certbot now for ${DOMAIN}? [y/N]:${NC} ")" RUN_CERTBOT
if [[ "${RUN_CERTBOT}" =~ ^[Yy]$ ]]; then
    info "Running certbot ..."
    certbot --nginx -d "${DOMAIN}"
    success "Certbot completed"
else
    warn "Skipping certbot. SSL certificates must exist at /etc/letsencrypt/live/${DOMAIN}/ before Nginx will start."
fi

# --- Reload ---

info "Reloading Nginx ..."
systemctl reload nginx
success "Nginx reloaded"

echo ""
success "Nginx setup complete for ${DOMAIN}"
